import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/api/provider";
import { ToastBar, Toaster } from "react-hot-toast";
import PersistProvider from "@/components/shared/PersistProvider"; // ← new
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Roots Beyond Dashboard",
  description: "Admin panel generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <PersistProvider> 
            {children}
          </PersistProvider>
        </ReduxProvider>
        <Toaster position="top-center" reverseOrder={false} />
        <ToastContainer position="top-center"/>
      </body>
    </html>
  );
}